### ISSUE TITLE
SimulationTimeSeries: allow selecting more vectors

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#1022]
Remove (or increase, do some testing) limit for max selected vectors in `SimulationTimeSeries` 

The new `SimulationTimeSeries` is significantly more responsive, and supports wildcards which makes it easy to select a large number of vectors. Natural to increase the limit

**Comment by jorgenherje** [comment]
Does now support up to 100 vectors (way more than needed) while using the `VectorSelector`.
