### ISSUE TITLE
SUMO compatible `SimulationTimeSeries` plugin

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#1049]
* SUMMARY export from Drogon with metadata. - `fmu-dataio`
  * Metadata definitions (`unit`, `is_rate`, `is_cumulative`, `vector_name`) - `fmu-dataio`
* SUMO upload of the SUMMARY data - `drogon model`
* Partial reading of SUMMARY data from SUMO - `sumo/sumo-explorer`
  * Other use cases is parameter analysis (all vectors for a given date across all realizations).
  * Sometimes only the statistics is needed (not all realizations) 
* Webviz: Support SUMO as source in SimulationTimeSeries - `webviz-subsurface`

* consider "timeseries" as content, and "summary" as source?

---

* should column level metadata be searchable?
* get all available vector names from ensemble
* some way with the metadata to link RMS well name, Eclipse well name, PDM well name and official well name (global config?)

* observation data

**Comment by perolavsvendsen** [comment]
testing what a task will look like:
- [ ] My task

**Comment by anders-kiaer** [comment]
Done, implemented in cloud-native repo `equinor/webviz`.
