### ISSUE TITLE
 `SimulationTimeSeries` items can not be chosed in Vector calculator 

### ISSUE THREAD

**Issue by JinCheng2022** [equinor/webviz-subsurface#1101]
**Describe the bug**
In the _Time series_ settings, the vector calculator works well when the dialog data is not updated. But when the callback is added, the items can not be chosen.

**How to reproduce**
1. Go to `Simulation time series`
2. Click on `Time Series`
3. Click on `VECTOR CALCULATOR`
4. Click on any item on the left side
5. See error: the CLONE and DELETE can not be clicked

**Comment by jorgenherje** [comment]
Closed by: https://github.com/equinor/webviz-core-components/commit/adbe93f13ce1c9a73b715f1d89aa94afd2975f9b
