### ISSUE TITLE
MonteCarlo ensembles classified as sensitivity_run if real-0 is default values in design matrix.

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-subsurface#1140]
In the class `ParametersModel` there is a function `_check_if_sensitivity_run()` that classifies each ensemble as a sensitivity run or not. The classification is done based on the values in the SENSNAME/SENSCASE columns. 

The problem comes if realization-0 in a montecarlo case is defined with defaultvalues. It will then have SENSNAME=defaultvalues/SENSCASE=ref, while the other realizations have SENSNAME=montecarlo/SENSCASE=p10_p90. This causes the `ParametersModel` to classify the ensemble as a sensitivity run since it requires the SENSNAME/SENSTYPE to be unique in a monte carlo run. Se code below. 

Some functionality will then not be available f.ex in `ParameterAnalysis` and `RftPlotter`.

```
        self._sensitivity_ensembles = [
            ens
            for ens, df in self.dataframe.groupby("ENSEMBLE")
            if not (df["SENSNAME"].nunique() == 1 and df["SENSTYPE"].unique() == ["mc"])
        ]
```

**Comment by lindjoha** [comment]
@tnatt @tralsos

**Comment by lindjoha** [comment]
A simple quickfix is to set SENSNAME=montecarlo/SENSCASE=p10_p90 in the parameters.txt file in realization-0.

**Comment by tralsos** [comment]
This is a user choice, to set up the designmatrix for a full montecarlo run together with a reference realisation, so it is understood as a one-by-one design. SENSNAME is chosen by the user for both the reference sensitivity and the monte carlo sensitivity.  A quickfix that the user can do is either to change the SENSNAME and SENSCASE in the designmatrix before running the ensemble, or change it in parameters.txt afterwards. Or the reference sensitivity could be run in a separate "ensemble". 

If webviz allowed for selecting an ensemble as a range of realization numbers (e.g. 1-99) it could be split out there as a separate ensemble.  

Not sure we should generally classify it as a bug. In some analysis it is useful being able to separate out the ref realisation, like in volumetric analysis seeing the spread of the mc ensemble compared to the single reference realisation. (But it would of course be better if the default to plot at startup was the mc sensitivity and not the ref sensitivity, which can be a bit confusing)  But it would be good if the ParameterAnalysis did not fail, e.g. that it just plotted all realisations in the ensemble it got. To tailor it to this specific case gets complicated; if it finds two SENSNAME and one of them only has one realisation which is of SENSTYPE scalar and the rest are of SENSTYPE mc it could drop this single realisation and keep the rest.

**Comment by tnatt** [comment]
I see the issue.. hm not sure what is the best solution actually. Maybe adding a sensname_sencase filter to ParameterAnalysis?

At least if the user has this default ref case at realization 0 you could remove it when defining the ensembles inside Webviz like this:
"SCRATCHENSEMBLE/realization-[!0]*/iter-0" instead of taking them all by using just the star.
(but these glob syntax are very limited and not many are aware how to use them...)

**Comment by lindjoha** [comment]
Yes, I agree it's not really a bug, but most users will have no idea why they don't see that page in `ParameterAnalysis` (and in the `RftPlotter`), and then they will not know how to fix it.

Can we fix it by recognizing the ensemble as montecarlo even if it has a defaultvalues realization? Or are there cases where actual sensitivity runs then would be labelled montecarlo?

**Comment by tnatt** [comment]
What if we never hide those pages, but we add a filter (or a dropdown) like this where you only can select one at a time? 
That could actually be quite useful for the cases where you set up sensitivities that are a combination of montecarlo parameters (like the one named "fwl_mc" in the drogon set).

The reason I hid the page was to avoid people interpreting correlation results from a sensitivity run in the ParameterAnalysis (I saw that several times).
![image](https://user-images.githubusercontent.com/61694854/198233441-48cb4faa-c046-4be5-a262-d000730855a2.png)

**Comment by tralsos** [comment]
That could be a solution. I guess correlations should not be calculated for more than one senscase at a time, and perhaps only be shown for cases of type "mc"

**Comment by lindjoha** [comment]
Good solution I think! We could hide the filter if there is only one case of type "mc", but that is details.
