### ISSUE TITLE
Demo app link broken

### ISSUE THREAD

**Issue by Coding-with-Adam** [equinor/webviz-subsurface#1204]
hi, I'm trying to view the demo app link, but it appears to be broken. Would it be possible to redeploy the app so it starts working again?

**Comment by HansKallekleiv** [comment]
Hi. You mean this link? https://webviz-subsurface-example.azurewebsites.net/

It might have been down temporarily, but it should be working now.

**Comment by Coding-with-Adam** [comment]
Thank you, Yes, I see it's working now. I appreciate it.Adam SchroederOwnerCharming Data LLC 118 E 124th ST #1808, New York, New York 10035   My Pronouns: He, him, his ¡Hablo español! 
      
        
        
          On Apr 11 2023, at 8:28 am, Hans Kallekleiv ***@***.***> wrote:
          
        
        
          
Hi. You mean this link? https://webviz-subsurface-example.azurewebsites.net/
It might have been down temporarily, but it should be working now.
