### ISSUE TITLE
Support Python3.11

### ISSUE THREAD

**Issue by larsevj** [equinor/webviz-subsurface#1255]
With the ongoing movement towards RHEL8 and Python3.11 for komodo, please consider adding Python3.11 support.

**Comment by asnyv** [comment]
depends on https://github.com/equinor/webviz-config/pull/675

**Comment by eivindjahren** [comment]
We are starting to build with python 3.11, but run into this problem: 
```
webviz-subsurface 0.2.25.dev6+gdef9a93 has requirement opm<=2022.10,>=2020.10.1; sys_platform == "linux", but you have opm 2023.10.
webviz-subsurface 0.2.25.dev6+gdef9a93 has requirement pandas<2.0,>=1.1.5, but you have pandas 2.2.1.
```
