### ISSUE TITLE
Feature request - simulation time series

### ISSUE THREAD

**Issue by sge-gatsby** [equinor/webviz-subsurface#214]
I have spent only very little time with webviz,  but as user I would like to:

-	Be possible to include the delta of the new well (even if it is not defined in both ensembles…, I guess if missing from one ensemble could be assumed that all parameters in that ensemble are zero). 
-	I would like to see more deltas included in one plot (i.e,. to compare different deltas between several ensembles…, or maybe in the plots below. Here I'm thinking of comparing (for example) the same reference case but for 2 IOR projects (i.e. 2 different well locations), but also different reference cases and their corresponding IORs...
-	I would also like to switch between possibility of using statistics (only) and the whole ensemble (including statistics), or only ensembles without statistics, or only some chosen statistics (i.e. only P10s).

That’s all for the time being! 😊😊😊

**Comment by jorgenherje** [comment]
PR https://github.com/equinor/webviz-subsurface/pull/867 closes request for multiple deltas in one plot. The statistics options are already handled in PR. https://github.com/equinor/webviz-subsurface/pull/867

Should this issue be closed @anders-kiaer ?

**Comment by anders-kiaer** [comment]
I think we can close this now, after #867. There might be some details remaining, but if that is the case let us specify them in a stand-alone issue highlighting those.
