### ISSUE TITLE
Parallel coordinates with color based on running time?

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#231]
When running AHM, there are usually some realizations that fail. If the failed realizations have roughly the same parameter values, the posterior might be biased. Some way of indicating/visualizing if failed realizations forms cluster in the "parameter space" would be nice.

Maybe [parallel coordinates](https://plot.ly/python/parallel-coordinates-plot/) with parameter axis together with coloring based on running time (or binary success/failure) could be an option.

**Comment by asnyv** [comment]
Closed by #265
