### ISSUE TITLE
Tornadoplot: Add tornado table

### ISSUE THREAD

**Issue by tralsos** [equinor/webviz-subsurface#236]
These are numbers that are often reported and would be useful to have in a table.
Perhaps same info as you already have in the plot, but open for other suggestions.

Example of what it could look like:

**Sensitivity compared to reference `<reference average name>` with average value `<ref avg value>`** 

Sensitivity | lowcase | highcase | delta low  | delta high | true low | true high | low #reals | high #reals
------------|----------|-----------|------------|-------------|-----------|----------|------------|----------
rms_seed | p90 | p10 | -3.42 | 3.24 | 1.114e+08 | 1.192e+08 | 10 | 10 
gwc | shallow | deep | -12.12 | 13.89 | 1.014e+08 | 1.315e+08 | 10 | 9

* Sorted in the same way as tornado plot, highest sensitivity on top.
* delta low always lower than delta high, and casenames flipped also if values are flipped (like for the labels on the plot)
* delta low/delta high are delta values with respect to reference. Could be either percentage or absolute (i.e. the same as for calculated in plot). 
* true low and true high are values where reference is not subtracted
* reals low and reals high are how many realisations that went into the low and high calculations

**Comment by anders-kiaer** [comment]
One possible way of solving this, which would be quite easy and without taking much visual space, is to let the sensitivity plugins get a "data download" button (which all plugins easily can implement using `webviz-config` core functionality). E.g. when the user clicks on the data download button, he/she will download the data currently visualized to e.g. `.csv`, which then can be taken further to reports, or spreadsheets for further custom calculations.

What do you think @HansKallekleiv @tralsos?

**Comment by tralsos** [comment]
I think it is the Tornado plot and the Tornado table that is most central for the sensitivity studies, so I would rather have moved the Tornado table left on the page and had the Tornado table visible. Then had the box plot to the right on the page with a downloadable table. I think BKH also commented in his input on slack that it would be better to have the tornado plot bigger and the tornado table visible ?
