### ISSUE TITLE
PVT data

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#26]
Plugin for analyzing and visualizing PVT models used in reservoir simulations.

**Comment by anders-kiaer** [comment]
This task is currently assigned [Ceetron Solutions](https://www.ceetronsolutions.com/visualization).

**Comment by anders-kiaer** [comment]
After discussion with Ceetron yesterday, this is currently the scope of this plugin:

- Read PVT data (e.g. using `opm-io` Python bindings).
- Show for the different fluids.
- Possibility to show mutliple `PVTNUM`s in same plot (for easier comparison).

Later/future enhancements (would be a separate issue/task):
- Extend to also visualize PVT uncertainty (when that is more standard in FMU).
- Include grid data / simulation data (e.g. how in the PVT curves are the different cells distributed as a function of time?)

**Comment by asnyv** [comment]
Sounds like a good place to start, have some questions:

If your are not going to handle uncertainty from the beginning, how do you choose where to get the data from? We cannot exclude the possibility that users might have included some PVT uncertainty on their own, so the data source should be well defined.
Options off the top of my head:
- First realization that has data (difference between ensembles should at least be supported, for e.g. a model update with new PVT data)?
- User specified input? 
- Check all realizations and make sure that they are equal?
   - In this scenario: Should we have an option to read PVT data dumped to `csv` in the realizations similar to how we do with relperm (I see that there are already `pvt.csv` files in our test data realizations). Dependent on speed of `opm-io` relative to the too slow `ecl2df` (at least for relperm). If `opm-io` provides a much more efficient data collection, we probably want to use that for relperm as well later on (if possible), but I still have a feeling that `opm-io` will be a lot slower than a `csv` solution for postprocessing of an ensemble.

**Comment by anders-kiaer** [comment]
Closing this in favor of #396.
