### ISSUE TITLE
Relative permeability

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#27]
Container for analyzing and visualizing relative permeability models used in reservoir simulations.

**Comment by asnyv** [comment]
Current plan, open for input:

Current idea is to try to do something fairly close to ReservoirSimulationTimeSeries, though with saturation as x-axis:
- Should be possible to plot multiple ensembles to compare distributions.

- Should be possible (differently from ReservoirSimulationTimeSeries) to plot different vectors in the same plot from the same ensemble (instead of individual plots). E.g. both kro and krw vs Sw in same plot. In this case, the vectors should get the standard coloring of red for krg, blue for krw and green for kro. Capillary pressure black. Should not be possible to plot vectors with different saturation axes (e.g. Sg and Sw).

- Data will come directly from input data through ecl2df.

- Will be on the big picture (realization) level, which means that their will be no adjustment for e.g. endpoint scaling, which would require a cell-by-cell process.

**Comment by berland** [comment]
Suggest to set aside space for plotting the SCAL recommendation (pess-base-opt) as an envelope alongside each curve. Not certain where to get these from yet (but somehow through the input sheet given to pyscal), but keep in mind. 

Either one plot pr. SATNUM (over all realizations), or all SATNUMs in one realization in the same plot. Both are in general relevant, but not for all reservoir models. 

Consider if family 1 style only should be supported, or family 2 style also should be an option. If coded cleverly, I think it is possible to flip between them visualization wise. I think the ecl2df output differs depending on whether it is family 1 or family 2 keywords that went in.

**Comment by asnyv** [comment]
@berland Agree that we should aim to have an option to add a SCAL recommendation. Didn't quite get what you meant with _set aside space_? Do you want to have the envelope in a separate plot? Would think it's natural to have the SCAL recommendation as three lines in the same figure?
As source I think we could require that the user provides a valid path to such a pyscal input sheet in the configuration, but we would have to decide on whether it is a per ensemble configuration, or if a single sheet is ok. We have to think about the amount of data  in the view and number of options in the plugin, not for performance, but to make it easy to understand. Therefore think it might be ok to disallow specification of SCAL recommendations per ensemble, and instead just have a single specified reference sheet.

Plot per SATNUM is clearly needed. Do you actually think it is necessary with all SATNUMs for a single realization, or is it ok to plot all realizations in the ensemble, and color by SATNUM? Similar to what is done per ensemble for simulation vectors in the picture at the end? Not sure if I like the idea of filtering on single realization unless you think there is a use case for it. Will include the ability to hover over a curve and get key information like ensemble, realization and saturation + relperm at nearest datapoint.

For data I think we should allow all types that are currently in [ecl2df](https://equinor.github.io/ecl2df/_modules/ecl2df/satfunc.html#df), which is family 1 + most of family 2. I haven't tested a set of family 2, but I assume that the `KEYWORD_COLUMNS` are what you get out? (actually, when I look at it, I think there might be some errors there, `SOFN` doesn't exist in the Eclipse manual, and a few are missing). The formats aren't that different, but I think it is reasonable to only show family 1 data as long as any of the family 1 keys exist (in any of the ensembles)? Would think that most models use family 1, and having a front-end switch between families introduces more confusion than gain in my head.

![image](https://user-images.githubusercontent.com/47146384/77542138-0114fa80-6ea6-11ea-9fe3-25a7aadbc9cf.png)

**Comment by alifbe** [comment]
For our upscaling project, we made a custom plugin to plot relative permeability and capillary pressure. There are some options that I think will be nice to have.
- option for flipping between the linear and semi-log plot.
- choose different SATNUM
- plot capillary pressure together with relative permeability
- set different opacity, in our experience, the curves can get very messy (depending on the range of LET parameters), setting opacity allowed us to tone them down.

![image](https://user-images.githubusercontent.com/11570927/77754657-08fea700-702c-11ea-8902-1e03f15aa27a.png)

**Comment by asnyv** [comment]
Thanks, @alifbe!
Short comments: 
- Linear and semi-log makes sense, and I will include that 👍 
- SATNUM and capillary pressures are already in the scope (plotting capillary pressures at a secondary axis as the range can be outside 0-1)
- Opacity will be considered, but a bit reluctant to adding more buttons and complexity than strictly necessary. Will have a "statistical fanchart" option similar to in the "Simulation time series" plugin of the demo which provides a less messy plot. Think that might cover your needs?

**Comment by alifbe** [comment]
@asnyv That's great. 'Statistical fan chart' might be a better option than transparency.

I think you might want capillary pressure in another plot, to avoid the mess. 

Looking forward to seeing the plugin.
