### ISSUE TITLE
Tornado plot tooltips outside figure

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#279]
Ensure that hover labels are within the boundaries of the tornado plot.

**Comment by anders-kiaer** [comment]
Maybe it can (partially?) be mitigated using the attribute [`overflow: visible`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overflow) on the `svg` element created by `plotly`.

**Comment by asnyv** [comment]
Sounds like a dirty "solution" in my opinion, tornado plots in several plugins are placed on the side of the view (like on the picture below). They have a bit more space due to the margins that we could overflow, but don't think we would be safe. A preferable behavior could be that the tooltips flip inwards if they start within the first or last quarter of the x-range (similar to how they now tip downwards in the upper half and upwards in the lower)? But it introduces a risk of overlapping if the width of the tornado plot is small.
![image](https://user-images.githubusercontent.com/47146384/78000573-c9d69b80-7334-11ea-8dcf-76743f6c353c.png)

**Comment by anders-kiaer** [comment]
Yes, I was thinking more of doing both. Do some real changes to the `plotly` arguments (if possible), but at the same time allow for `overflow: visible` (to further help e.g. in rare/extreme situations).

**Comment by asnyv** [comment]
That sounds better 👍 could also have straight up/down tooltips for narrow tornado charts instead of tilted, to reduce overlap risk. (But tilted should be kept if possible as it is far easier to read)
