### ISSUE TITLE
Utilize metadata from fmu-ensemble

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#284]
Utilize https://github.com/equinor/fmu-ensemble/pull/89 in `webviz-subsurface`.

E.g.:
- more robust detection of historical vs. non-historical vectors
- more robust split of vector name vs. node name.
- show human-readable y-axis labels
- time series interpolation method based on vector type (cumulative vector linear interpolation, rate vector backfilled). See [`linear` and `vh` interpolation in `plotly`](https://plotly.com/python/line-charts/#interpolation-with-line-plots).

**Comment by asnyv** [comment]
Sure about the backfill/vh for rate @anders-kiaer? Think Eclipse behavior is the opposite? 🤔

**Comment by anders-kiaer** [comment]
> Sure about the backfill/vh for rate @anders-kiaer? Think Eclipse behavior is the opposite? 🤔 

Not 100% sure - but I think last time I checked Eclipse write rates to UNSMRY such that they should be interpolated backwards until the previous report step.

I.e. if I recall correctly, if you have a WCONHIST entry at a specific date, it is the next report step in the UNMSRY that will have the new rate given in WCONHIST.

**Comment by thor85** [comment]
I think I remember history and prediction is opposite? So WCONHIST is backward and WCONPROD is forward?

**Comment by asnyv** [comment]
> I think I remember history and prediction is opposite? So WCONHIST is backward and WCONPROD is forward?

Hopefully this is not the case, but wouldn't be _that_ surprised.

**Comment by asnyv** [comment]
For anyone interested I ran a controlled simulation and processed it different ways to remove all doubt. Probably removed doubt of the original question, but raised a ton more 😞 

Think we can conclude that there are no difference in WCONHIST and WCONPROD/WCONINJE. When you set them in the schedule, both define the rate going forward until it is redefined.

Directly from the UNSMRY I would say it is most correct to interpolate backwards in the case that you have raw data as @anders-kiaer proposed ("unfortunately" for my original claim 😉) .

When the data is interpolated by fmu-ensemble/ecl2df, as it often is in our case, we could probably still consider to interpolate backwards, but as you can see from the yearly data in the link below; it it is risky to not backcalculate from cumulatives. On the other hand, that smears out the rate and gives a false impression that the well produced/injected over a longer period of time. Both methods have their drawbacks. Could be that leaving it at 0 (for the yearly example in the xlsx-file below) and having a checkbox (or similar) for averaged rate (#292) is the best?

A more challenging question is how to handle other vectors (not rates/cumulatives):
Have checked two other plotters as reference (ResInsight + a completely external)
E.g. (near) well/group pressures (WBHP, WBP, WTHP++) probably interpolated backwards, with region/field linear to fit cumulative volumes? (ResInsight does backwards for region/field, the other one linear)
Water-cut: I would think backwards to fit with rate, but seems like my reference plotters (ResInsight and another external one) both do linear. Should be similar with GOR.
WPI should probably be backwards
Inplace: resinsight does backwards, the other one linear. I would say linear (again to fit cumulative volumes).
And I could go on and on and on...

The **BIG** question is therefore: Shall we really hardcode our impression of the most reasonable interpolation method for any vector type? 🤔
[simpel_model_test.xlsx](https://github.com/equinor/webviz-subsurface/files/4444172/simpel_model_test.xlsx)

**Comment by asnyv** [comment]
Additional comment to this: 

Was proposed to use the summary metadata from `libecl` (e.g. `is_rate`, `is_total`) to simplify this (backwards on rate, otherwise linear), but this seems to be risky, some examples:

- `WVPR`/`GVPR`/`FVPR` are described as _Reservoir Volume Production Rate_ and should therefore return `True` for `is_rate`, but returns `False` in my test (Note that the cumulative versions of these, `FVPT` and etc, have `is_total=True`)
- `GVIR`/`FVIR` (I lacked `WWIR` in my test). Injection rate at reservoir conditions, but `is_rate=False`
- `WWCT`/`GWCT`/`FWCT` are water-cuts, and is `True` for `is_rate` from libecl, though they aren't. (Though a rate like behavior in our case probably is ok)
- `WGOR`/`GGOR`/`FGOR`.  gas-oil-ratio, same situation as for water-cuts. Returns `is_rate=True`
- `FWGR` (lacked `WWGR` and `GWGR` in test). Water-gas-ratio. Returns `is_rate=False` which is opposite of water-cut and GOR...  
- `WPI`, productitivity index for well, `is_rate=False` which is true, though I would say that it would be reasonable with the same behavior as for water-cut and gor.
- pressures seem to overall be `is_rate=False`, which is ok. Same applies to in-place (though I would prefer to interpolate the latter linearly)
- `WGLIR`/`GGLIR`/`FGLIR` are gas lift injection rates, which are clearly rates, but I get `is_rate=False`
- `GGPP`/`FGPP` (lacked `WGPP`). Gas potential production rate `is_rate=False` (same applies to oil and gas equivalents.

Test with random (not existing vector): Returns `is_rate=False`, `is_total=False`, so might be hardcoded vectors somewhere, and returning `False` if it is not found.

**Comment by asnyv** [comment]
Looks very likely @anders-kiaer. For us it is probably best to modify the libecl to fit our purpose, as they have already included non-rates like water-cut and GOR in `is_rate=True`. But might of course become a question of how much we can modify. Think to have a sort of system our aim has to be that as many as possible of the vectors that are discontinuous when switching controls (open/close wells, and etc) are backfilled, while the rest are interpolated linearly. That includes (but not limited too):
- Rates (production, injection, gas lift, tracer and probably more)
- phase ratios (gor, wct, wgr and etc)
- PI (WPI, WPI9 and etc)
- Pressures in the flow network nodes, in well + near well (WBP)
- States of controls (WMCTL, WSTAT, [F,G]MCTP, [F,G]MCTW)
The more I think of it, the more I feel like it migth be better to go the opposite way, e.g. backfill as default, and linear if in-place, total, or reservoir pressures, but there are probably a ton of exceptions this way as well. Looking into what ResInsight did could be a way to go as well.

**Comment by anders-kiaer** [comment]
> Looking into what ResInsight did could be a way to go as well.

Here are perhaps some relevant ResInsight information:
- https://github.com/OPM/ResInsight/issues/1893 (this might be a good idea - i.e. do step/linear where one of them is obviously the correct one, and let the user decide with a "default" setting for the non-obvious cases?)
- This looks like the ResInsight logic on determining if to plot using backfill or linear:
   - [Main function](https://github.com/OPM/ResInsight/blob/0b47e27e8927ba571e377c70551cb193bee1c6f1/ApplicationCode/ProjectDataModel/Summary/RimSummaryCurve.cpp#L1126-L1140)
   - [Helper function to decide if it is cumulative data](https://github.com/OPM/ResInsight/blob/0b47e27e8927ba571e377c70551cb193bee1c6f1/ApplicationCode/FileInterface/RifEclipseSummaryAddress.cpp#L801-L814), which perhaps explains why you observed linear interpolation for `WWCT` @asnyv?

Might be that @magnesj and @hhgs have something to add based on ResInsight development/experience. 

Regardless, I think we could make a small fix to `libecl` adding the obvious missing vectors in the `is_rate` and `is_cumulative` `libecl` functions. Do you want to make a mini-PR there @asnyv?

**Comment by hhgs** [comment]
ResInsight checks self for cumulative vectors ending on "T" or "TH" (*WCT to be excluded).

**For non-cumulative vectors:** 
- Default is "Step Left" , but user can select "Point to point" interpolation. 
- Better visualization alternative for "Point to Point" would be "Midpoint to Midpoint" (ref illustration https://github.com/OPM/ResInsight/issues/5807). 

**For cumulative vectors:**
- Default is "Point to Point" (no other alternatives seams relevant).

**Comment by asnyv** [comment]
> Better visualization alternative for "Point to Point" would be "Midpoint to Midpoint" (ref illustration OPM/ResInsight#5807).
is it @hhgs? Felt we had concluded above here that for e.g. rates, the only reasonable is "step left", as that is what is used in the Eclipse time step?

**Comment by asnyv** [comment]
> Regardless, I think we could make a small fix to libecl adding the obvious missing vectors in the is_rate and is_cumulative libecl functions. Do you want to make a mini-PR there @asnyv?
Sorry, forgot to answer you on this @anders-kiaer, but I made one a couple of days ago https://github.com/equinor/libecl/pull/707 still waiting for feedback from admins.

**Comment by hhgs** [comment]
"step left" illustrates more correctly Eclipse simulation results, but sometimes the user would like to have interpolated curves, for smoother presentations or cases where interpolation gives more separation between curves in the plot, hence makes it easier to read.

**Comment by asnyv** [comment]
@hhgs ok, can agree on that, but think that at least for rates, node pressures like bhp and etc, it can be confusing of midpoint-to-midpoint is default as suggested in the ResInsight issue. Could make plots that don't fit with input in wconhist/wconprod and etc...
