### ISSUE TITLE
Remove warning from xtgeo

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#285]
With the latest `xtgeo==2.7.1`, and using `webviz-subsurface-testdata`, we get 6346 warnings of the type
```
WARNING: 	Masks differ, not consistent with 'strict'
```
Either change the code in `webviz-subsurface` or the testdata in `webviz-subsurface-testdata`, in order to get rid of the warning.

**Comment by anders-kiaer** [comment]
This currently appears during CI of #283.

**Comment by anders-kiaer** [comment]
Related https://github.com/equinor/xtgeo/pull/328.

**Comment by jcrivenaes** [comment]
https://github.com/equinor/xtgeo/pull/328 is merged to master
