### ISSUE TITLE
Show statistical averaged rates

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#292]
Feature request for showing statistical averaged rates, as well as total volume, within a given time sampling (e.g. over a month or year). Due to the way Eclipse defines and writes output vectors, it will be necessary to use cumulative vectors as basis for the calculation (and then take time deltas over the requested time sampling interval).

**Comment by asnyv** [comment]
Should be quite easy to implement as long as the time sampling is supported by `get_volumetric_rates`  in `fmu-ensemble`. But in that case the sampling options should probably be predefined by the user (or defaulted), so that the average rates are calculated during building.

**Comment by asnyv** [comment]
Been looking a little bit on this. 
A few additional comments/questions:
- Do we want to incorporate all of this into the ReservoirSimulationTimeSeries plugin? All the requested features makes sense as a time series graph, but at least the totals per month, year and also feels natural in a tabular view, so in that case #326 should also be considered.
- What do we call these vectors if we mix them in the same plugin with regular Eclipse vectors?
- How to compute: In theory, `fmu-ensemble` supports all the requested features: averaged rates and cumulatives over a time sampling. The big question is: How much do we want to precalculate and store during build?
  Some options:
  1. Tested a bit of on-the-fly calculation using `VirtualEnsemble` in `fmu-ensemble`, created on the summary DataFrames that we are already storing for eclipse vectors. By using this we could have all these features on request, without storing more data during build. Unfortunately it seems to be far too slow for interactive use.
  2. An alternative which is probably the easiest to implement, and would give the most responsive plugin, is to precalculate all options using `fmu-ensemble` during build. That is e.g.: Time series in volumes per day, month and year. Would also require most storage.
  3. A hybrid, e.g. calculating average rates per day, but leaving aggregation to time sampling to the webviz plugin.
  4. Not use `fmu-ensemble`

  I lean towards option ii., precalculating and storing volumetric rates per day + monthly and early delta cumulatives; as it is probably the easiest way (together with i., which seems too slow), and leaves most of the logic upstream of `webviz-subsurface`.

**Comment by anders-kiaer** [comment]
> Do we want to incorporate all of this into the ReservoirSimulationTimeSeries plugin? All the requested features makes sense as a time series graph, but at least the totals per month, year and also feels natural in a tabular view, so in that case #326 should also be considered.

I vote for having it in the same plugin. Most (all?) of the existing buttons are also relevant here I think (even delta).

> What do we call these vectors if we mix them in the same plugin with regular Eclipse vectors?

Two options I guess. Either we add a UI element (which enables the users to choose between "time series" and "bar charts"). Then naming is easy (difficult to misunderstand). The cost is an additional UI element. The other is differentiate on name only.

> iii. A hybrid, [...], leaving aggregation to time sampling to the webviz plugin.

How much time does it take to e.g.
- linearly interpolate a given vector for all realizations to a common given time array
- take one step delta
- calculate mean/percentile/std

Preferably using core `numpy` functions (or `pandas` functions interfacing C code). Is that also too slow?
