### ISSUE TITLE
Vector calculator (simulation time series)

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#293]
It can be useful to combine existing vectors (e.g. simulation time series) to a new vector by the use of simple mathematical operators like `*`, `^`, `/`, `+`, `-` and `()` at the realization level. Would have to be up to the user to make sure that the expressions make sense. The expressions should by possible to make on-the-fly, but could preferably also be an option to pre-define a set of expressions that are calculated when building the app, both for performance, but also so that the user doesn't have to recreate "standard" expressions every single time. 
Similar expressions can usually be made in reservoir simulators (like Eclipse UDQs), but they are not completely straight forward to implement, and require rerunning the simulations.

**Comment by rubenthoms** [comment]
First draft of how the vector calculator could look like. This is in order to have a common foundation for further discussion.
![Web 1920 – 1](https://user-images.githubusercontent.com/69145689/102103840-c7b65d80-3e2d-11eb-990f-21b8b1f7acb3.png)

**Comment by jorgenherje** [comment]
Closed by PR: https://github.com/equinor/webviz-subsurface/pull/709
