### ISSUE TITLE
Data download / Table view for ReservoirSimulationTimeSeries

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface#326]
A user wants to see the currently visualized vectors in a table format.
Display tables in webviz (as a separate tab?) or add data download functions.

**Comment by anders-kiaer** [comment]
Also covered by #276.

**Comment by anders-kiaer** [comment]
AFAIK, we haven't seen this user request pop up again (wrt. table) after adding possibility to download data to csc/excel. Closing.
