### ISSUE TITLE
Bootstrap CSS

### ISSUE THREAD

**Issue by saeedfb** [equinor/webviz-subsurface#416]
Thanks for the great product. Wondering if it is possible to use Bootstrap syles and if yes, how it can be implemented. Appreciate the help.

**Comment by anders-kiaer** [comment]
Hi, any plugin can add custom assets (and `javascript` + `css` files will automatically be loaded for you by the framework). 

See here for an example:
https://github.com/equinor/webviz-subsurface/blob/8b0a29095aeab4b4c10de5d70a9b9b225dbce00c/webviz_subsurface/plugins/_horizon_uncertainty_viewer/horizon_uncertainty_viewer.py#L52-L54

You also need to (as always for package data in Python) to explicitly tell `setup.py` to treat your files as something belonging to the package. E.g. something like in
https://github.com/equinor/webviz-subsurface/blob/8b0a29095aeab4b4c10de5d70a9b9b225dbce00c/setup.py#L16-L20

**Comment by saeedfb** [comment]
Tusen takk. Dette var det jeg trengte 👍
