### ISSUE TITLE
Slow libecl reading with large ensembles

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#418]
In use cases like e.g. [FlowNet](https://github.com/equinor/flownet), it takes a veeeeeeeeeeeeeeeery long time to extract `libecl` data (through the `fmu-ensembles`calls?). It also takes some time in large classical ensembles.

The `parquet` format supports metadata at multiple levels, and there are ways to also use that with `pandas`:
https://github.com/pandas-dev/pandas/pull/20534#issuecomment-453236538

Add (or extend) some forward model in [`semeio`](https://github.com/equinor/semeio/) to read+store time series + necessary metadata to `parquet`, and read that by default in Webviz if the file exists?

Opinions @asnyv @berland?

**Comment by berland** [comment]
I assume you are talking about pre-processing on realization level to some data format that is easier to parse later on. https://github.com/equinor/fmu-tools/pull/47 is an unfinished attempt at this, to make a standardized forward model that is being run on each realization, and where dumping to parquet or uploading anywhere would be possible.

The ERT api could be another possibility.

**Comment by anders-kiaer** [comment]
Related: https://github.com/equinor/webviz-config/issues/382

**Comment by anders-kiaer** [comment]
After the work with @sigurdp on reducing memory footprint, the next major framework improvement would be to reduce Webviz build time (it is very slow for large ensembles/models). A brief offline chat with @jcrivenaes and @perolavsvendsen confirms that something like what is sketched below would be in line with SUMO and FMU metadata/Drogon.

**Proposal:** Basically a very simple job that reads `.UNSMRY` using `libecl` on realization level (while still on the cluster) and dumps it raw to a open standardized, efficient binary format, e.g. compressed `.arrow` files or HDF5. Metadata (units, `is_rate`/`is_total`...) could be added as metadata to the same file.

Another use case of such a job would be to optionally, for certain selected vectors which are sparse by nature (`WSTAT` and grid cell completion status, e.g. `OPEN`, `SHUT`, `STATUS`) - to be stored "sparse" only (`.UNSMRY` would store `WSTAT` and grid cell cell completion for every time step, even though it easily could be ~99.9% redundant data). @lindjoha 

![image](https://user-images.githubusercontent.com/31612826/120180177-be6a5300-c20b-11eb-80cd-6ec0ecaf2c8c.png)

**Comment by anders-kiaer** [comment]
After #673 there is now a forward model dumping `,arrow` files (https://arrow.apache.org/overview/), which have shown crazy good read performance on RHEL when testing on real models.
