### ISSUE TITLE
Disable min-max shade

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#444]
A user has requested possibility of turning of min-max in e.g. `ReservoirSimulationTimeSeries` (ensemble has extreme values - sometimes easier to compare using p10-p90 as boundaries).

**Comment by asnyv** [comment]
Extended requests: 

- No shade (only lines): Easier to separate when plotting many cases, as the colors don't blend. 

- Possibility to select which active (e.g. min, max, mean, p10, p50, p90). With the current shading, that is a bit tricky. Easy for the lines in the first bullet point, so think might be ok to just have it there.

**Comment by anders-kiaer** [comment]
Considering this closed by #612.
