### ISSUE TITLE
TornadoPlot does not scale with number of sensitivities.

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#454]
**Describe the bug**
TornadoPlot in `OneByOne`-plugins should get higher if there are many sensitivity cases. Currently the labels can overlap, and the bars get very thin.

**How to reproduce**
Run a sensitivity study with many sensitivities, and view in e.g. the `ReservoirSimulationTimeSeriesOneByOne` plugin

**Expected behavior**
The TornadoPlot height should increase with the number of sensitivites included.

**Comment by anders-kiaer** [comment]
Closed by recent improvements in tornado viz.
