### ISSUE TITLE
Toggling history trace in legend only works on first vector in ReservoirSimulationTimeSeries 

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#458]
**Describe the bug**
Toggling the "History" in the legend only removes the "History" trace from the first vector if multiple vectors are plotted.

**How to reproduce**
1. Go to Simulation time series
2. Click on e.g. vectors FOPR, FGPR, FGPT
3. Toggle history be clicking at "History" in the legend
4. See that the black line only disappears in the uppermost subplot

**Expected behavior**
History trace should disappear in all subplots

**Screenshots**
Not toggled in legend, all visible (as it is supposed to be):
![image](https://user-images.githubusercontent.com/47146384/94655689-49065580-02ff-11eb-8c9c-278f0fe35b3f.png)
Toggled, still two history traces visible:
![image](https://user-images.githubusercontent.com/47146384/94655810-6fc48c00-02ff-11eb-803c-be5cd6310400.png)

**Additional context**
Can most likely be fixed by adding a constant `legendgroup` to `add_history_trace`
https://github.com/equinor/webviz-subsurface/blob/55033105f9acc48a45d69a38dd1010791d21c9e3/webviz_subsurface/plugins/_reservoir_simulation_timeseries.py#L1099-L1108

**Comment by robpoll** [comment]
I'd like to work on this issue.

**Comment by asnyv** [comment]
> I'd like to work on this issue.

Sorry @robpoll, as I had already identified the issue, and it was only one line to do it, I had already made the fix. But there are many other issues in the list 😉 😄

**Comment by robpoll** [comment]
Alright @asnyv. This project got my interest, so I'd like to contribute somehow. I'm new to this open source contributing, so something simple would be great for the beginning. What do you reckon?

**Comment by asnyv** [comment]
Not sure how familiar you are with subsurface simulation data? If you are not, maybe it is a good idea to start in the more generic library [webviz-config](https://github.com/equinor/webviz-config/issues)? `webviz-subsurface` is an extension of this directed towards ensemble based reservoir simulation applications in the petroleum industry.

**Comment by robpoll** [comment]
Unfortunately, I'm not familiar with that @asnyv. I'll have a look on issues in webviz-config, but I think without some guidance I wouldn't be able to really contribute and I'll have to look elsewhere.

**Comment by asnyv** [comment]
@robpoll Best place to start is probably to filter on "good first issues" in [`webviz-config`](https://github.com/equinor/webviz-config/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
They are a bit varied, several of them are focused on the framework itself, but if you prefer to work more towards the plugin side (similar to webviz-subsurface, which is mainly a collection of plugins for webviz-config), you can look at e.g. this: https://github.com/equinor/webviz-config/issues/297

**Comment by robpoll** [comment]
Alright, I'll have a look on that one. Thank you @asnyv. Will do so!

**Comment by robpoll** [comment]
After following the steps in readme.md, after running the command webviz it
says:
zsh: command not found: webviz

**Comment by asnyv** [comment]
@robpoll could you say exactly which steps you have made?

**Comment by robpoll** [comment]
These steps, but instead pip install -e . I used pip3.
[image: image.png]

**Comment by robpoll** [comment]
`git clone git@github.com:equinor/webviz-config.git
cd ./webviz-config
npm ci --ignore-scripts && npm run postinstall
pip install -e .
`
Instead of pip I used pip3.

**Comment by asnyv** [comment]
@robpoll  Could you try "pip freeze" (or in your case "pip3 freeze") to see if webviz-config is in your list of installed packages?

**Comment by anders-kiaer** [comment]
I would also try [rehashing](https://superuser.com/questions/490983/how-to-rehash-executables-in-path-with-bash) your terminal window (or simply opening a new terminal with the Python environment you installed it in activated). This could typically happen in general when what is available on your `$PATH`s changes.

**Comment by robpoll** [comment]
Well, I have here webviz-core-components==0.1.0
and I have a strange entry, which is 

> -e git+git@github.com:equinor/webviz-config.git@***a lot of characters***#egg=webviz_config

**Comment by anders-kiaer** [comment]
> and I have a strange entry, which is -e git+git@github.com:equinor/webviz-config.git@a lot of characters#egg=webviz_config

That is expected (when you install from unreleased source code, and not `pip install webviz-config`... more details here https://github.com/pypa/setuptools_scm).

**Comment by robpoll** [comment]
Thanks, I have created another venv and installed once again. Now it works!
