### ISSUE TITLE
Alternative Eclipse time series selection

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#469]
**Is your feature request related to a problem? Please describe.**
Users are used to hierarchical selectors for Eclipse vectors in other softwares, while we currently merge all into a single dropdown selector. This makes it a bit cumbersome to switch fast between wells/groups for the same vector, or between vectors for the same well/group. It also makes the available options quite hard to find, as you have to know what to search for.

**Describe the solution you'd like**
When we have Eclipse summary input, we are already able to extract quite a lot of metadata: like what kind of vector it is, which well/group it belongs to and units. Should be possible to utilize this for an alternative selection closer to existing softwares (e.g. ResInsight and other commercial viewers).
Typically:

1. Choose vector type: e.g. Field, Group, Well, Block, Misc and etc)
2. Choose subgroup (if relevant): e.g. which well or which group
3. Choose vector

It is also requested that you should be able to switch to e.g. the next well for the same vector with minimal effort.

Need to think about how me can make this relatively clean.

**Comment by anders-kiaer** [comment]
Solved by adding the `VectorSelector` in the recent `ReservoirSimulationTimeSeries` plugin. 🎉  It can probably be used in other plugins as well (lets have that task in a separate issue with reduced scope).
