### ISSUE TITLE
Deltas when realization is missing in one ensemble is set to 0

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#472]
**Describe the bug**
Deltas in ReservoirSimulationTimeSeries where one realization is missing is set to 0, [see end of this function](https://github.com/equinor/webviz-subsurface/blob/77dfbc6f151a8d705e7af28280486be684f5d3d3/webviz_subsurface/plugins/_reservoir_simulation_timeseries.py#L1012-L1026). This affects statistics.

**Expected behavior**
Should filter out realizations which don't exist in both ensembles.

**Comment by anders-kiaer** [comment]
👍 We should also check what happens if two realizations both exists, but have different set of vectors.
