### ISSUE TITLE
Fan charts assume mean between p10 and p90

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#488]
**Describe the bug**
The current fan chart implementation assumes that mean lies between p10 and p90. In addition, mean may be misleading in the case of discrete events (e.g. well is shut)

**How to reproduce**
Plot a vector for an ensemble where mean is outside p10-p90 (that means: the max or min must be "extreme")

**Expected behavior**
Mean has no robust way to be include, consider to switch to median (p50)

In addition: a mean could be added as an independent line, e.g. a dotted line in the same color as the median line

**Comment by anders-kiaer** [comment]
After #612 maybe we should simply do the switch as recommended above: Consider switch to median in fanchart? Mean is now possible in the statistical lines-mode

**Comment by jorgenherje** [comment]
Closed by https://github.com/equinor/webviz-subsurface/pull/719
