### ISSUE TITLE
User request: Multiple deltas in same plot in ReservoirSimulationTimeseries

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#502]
**Describe the solution you'd like**
Add option to plot multiple deltas in same plot in ReservoirSimulationTimeseries. 
Important especially in prediction to compare scenarios. 
User wants full freedom in ensemble combinations, (e.g. choose multiple ensemble A's and ensemble B's)

**Describe alternatives you've considered**
Personal view is that maybe a constant base ensemble ("ensemble B") is ok, even though I see a few use cases for full freedom.
Could alternatively be a checkbox to lock it (which e.g. by default is locked, but possible to let loose. 

**Additional context**
Challenge: How heavy will the computations be...?

**Comment by jorgenherje** [comment]
Closed by https://github.com/equinor/webviz-subsurface/pull/867
