### ISSUE TITLE
Container for quality check of realizations (failds ones etc.)

### ISSUE THREAD

**Issue by WestfalNamur** [equinor/webviz-subsurface#51]
Open questions:
- would this be its own container or an addition info others
- what to inlcude (faild realisations or more infos about ert? => maybe get some feedback form assets?)

**Comment by anders-kiaer** [comment]
After discussin with @asnyv, maybe something along these lines:
- The main visualization is a plotly heatmap.
- Down along vertical axis are the different jobs from the ERT workflow (maybe have an option to filter away trivial jobs like MAKE_DIRECTORY etc.?)
- Along horizontal axis are the realizations.
- Color of heatmap is either binary green/red (successfull/failed), or a colormap showing time spent (either relative to time spent for single job within that realization, or across the whole realization).

**Bonus:**
When running AHM, there are usually some realizations that fail. If the failed realizations have roughly the same parameter values, the posterior might be biased. Some way of indicating/visualizing if failed realizations forms cluster in the "parameter space" would be nice.
