### ISSUE TITLE
ReservoirSimulationTimeSeries cross-plot

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#514]
**Describe the solution you'd like**
Should be possible to cross-plot vectors (each point is one realization, at a single time, but two different vectors at x and y axis), instead of just as a function of time. 

Natural use case is e.g. pressure as a function of cumulative production, water-cut as a function of cumulative production and probably many more...

**Comment by anders-kiaer** [comment]
Solved now by #645?
