### ISSUE TITLE
not able to run webviz on mac

### ISSUE THREAD

**Issue by miroine** [equinor/webviz-subsurface#520]
Trying to create some simple plugins however faced a crash on #webviz due to issue with #opm installation which is not possible to install on #mac , I am not planning to use any #opm related feature ... so in theory #webviz should not crash due to that ? 
![image](https://user-images.githubusercontent.com/40567543/101093235-c4fc7280-35ba-11eb-8307-f0e282ef5488.png)

**Comment by asnyv** [comment]
Hi!

If you are only trying to create your own plugins, and you are not in need of the specific plugins of `webviz-subsurface`, you can install only `webviz-config`. This is the main webviz framework, and will enable you to create your own plugins, and run webviz. `webviz-subsurface` is a collection of webviz plugins directed towards subsurface models, of which some are `opm` dependent (either directly, or indirectly through other libraries like `ecl2df`).

Will that cover your needs? 

Just to make sure though: you have tested `pip install opm`, and it fails on Mac (OS X)? You don't need a full install of all OPM software like reservoir simulators and etc, just the python bindins to OPM-common

**Comment by miroine** [comment]
Hei 
was hoping to use some plugins from `webviz-subsurface` (where I mainly feed a `csv` file ...) so not really needing the `opm` .... `pip install opm`  fails on `mac` (ideal it should not fail but I guess that s way in the future .... ), I am using `webviz-config` now .... but then won t be able to continue developing on my mac for future integration :-(

**Comment by asnyv** [comment]
Think this one is going to be put on indefinite hold unfortunately @miroine. 

Seems like `ecl2df` is becoming a hard requirement in `fmu-ensemble`, as a lot of code is duplicated between the two packages, and `fmu-ensemble 2.0` is going in the direction of outsourcing data extraction (for table like data) to `ecl2df`. `ecl2df` has `opm` as a dependency, and `fmu-ensemble` is at the moment a core part of `webviz-subsurface` data extraction (likely until the day everything is served by APIs).

**Comment by asnyv** [comment]
maybe I'll take that back @miroine 😅 https://github.com/equinor/ecl2df/pull/268/files

**Comment by anders-kiaer** [comment]
We could probably do the same as `fmu-ensemble` and make parts of `webviz-subsurface` work without `opm`. :thinking: 

The best would of course be that upstream package supports requested OS. Have you created an issue in https://github.com/OPM/opm-common @miroine for your use case on Mac if it doesn't already exist? :rocket:
