### ISSUE TITLE
Dependency on fmu-ensemble

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#53]
Some `webviz-subsurface` containers want to depend on https://github.com/equinor/fmu-ensemble. Add it as dependency? Get `fmu-ensemble` on pypi first?

Probably requires changing the license from LGPL to GPL (however, e.g. `webviz-config` can keep LGPL due to it not being dependent on `webviz-subsurface` at all).

@HansKallekleiv @berland

**Comment by HansKallekleiv** [comment]
Is it an alternative having the necessary data already existing on /scratch? E.g. generated by ert / postprocessing? This would speedup Webviz and simplify dependencies. It would also make it easier for externals to use the containers. We would have to establish a required data input format for each container, usually csv files with standardized headers and name.

Thoughts?

**Comment by WestfalNamur** [comment]
If this dataset would be only used during testing and development (otherwise we would have to make on for each cluster) it is a good idea. Only data + webviz dependent and testing would be faster. As well a "standard" to refer to.

**Comment by anders-kiaer** [comment]
License changed to GPL.
