### ISSUE TITLE
Add unit converter for PVT data

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz-subsurface#534]
Some INIT files (and also PVT text files) contain data in unit systems different from SI (or Metric). It would be helpful to have a unit conversion support that can be used in any plugin/datainput. 

Suggestion is to start with PVT data and from there develop the feature further to be of general use.

**Comment by asnyv** [comment]
Should we rename it to just unit converter (starting with pvt)

To show that it is supposed to be generalized, just first round is for pvt?
