### ISSUE TITLE
Improve efficiency of summary metadata aggregation

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#539]
Currently the summary metadata is handled by a separate method in `fmu-ensemble`, which is about as heavy as the get_smry() itself, as it loads all the summary data. 

In `ecl2df` [it is now proposed](https://github.com/equinor/ecl2df/issues/241) to add this metadata directly to the pandas `DataFrame.attrs` for the dataset. The `DataFrame.attrs` is said to be experimental, so a bit risky to base on it, but there are some good opportunities. An alternative is something like returning a tuple of the `df` and a metadata `dict` instead of just the `df` if you set a flag. 
At least, `fmu-ensemble` is planning to base this part of the code directly on `ecl2df`, so then we could get the same feature there. 

On the webviz-side, the `pandas.to_parquet()` for portables doesn't support metadata directly, but according [to this article](https://towardsdatascience.com/saving-metadata-with-dataframes-71f51f558d8e) the route to combine a df and json-like metadata dict in a parquet file doesn't seem too hard. A feature to combine `df`s with metadata in our portables is anyways something I am sure that we can benefit from (unless reading the parquet back into pandas becomes a lot slower).

Think this can be a major gain in build time, and possibly also memory usage during build for apps using data from `UNSMRY`.

**Comment by asnyv** [comment]
Alternative path to quicker and more memory efficient aggregation of metadata from `SMSPEC` is to solve [equinor/ecl/issues/796](https://github.com/equinor/ecl/issues/796) and utilize that in `fmu-ensemble` / `ecl2df` with an implementation of the aggregation close to how it currently is (so a separate function for metadata as today in `fmu-ensemble`)

**Comment by anders-kiaer** [comment]
Today, from webviz side, we probably want to let the `.arrow` dump solve efficient memory metadata aggregation "automatically" (simply be being a good format for arbitrary reads). 🚀
