### ISSUE TITLE
Optional not include restart when loading smry.

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#559]
Relates a bit to https://github.com/equinor/webviz-subsurface/issues/545

In [fmu-ensemble's get_smry()](https://github.com/equinor/fmu-ensemble/blob/82cf5fa4b76a4f0c1c39548bff91eff387e92e33/src/fmu/ensemble/ensemble.py#L1322), you may set the defaulted `include_restart=True` to `False`. This will skip restart data from simulations you have restarted from, which may reduce the amount of data by a lot for predictions in fields with a long production history.

**Comment by anders-kiaer** [comment]
With the new suggested `.arrow` job not including restarts will be the default: https://github.com/equinor/webviz-subsurface/blob/3cf03cbef68a7120471a771eb11dbd7dc6fa1538/webviz_subsurface/ert_jobs/smry2arrow.py#L92

Plan is then to "include" restarts again visually when doing #623.
