### ISSUE TITLE
Surface/map comparison viewer

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#63]
- [ ] Interval thickness maps
- [ ] Difference maps, eg.
    - initial vs. modelled isochore
    - old versus updated structure

**Comment by HansKallekleiv** [comment]
I believe we have the necessary visualization in place with https://github.com/equinor/webviz-subsurface-components/pull/17.

In addition we need a webviz container that reads surfaces from disk, and that can do some calculations between surfaces.
The main challenge is the data input / configuration specifying where the surfaces are coming from and how they are organized.
