### ISSUE TITLE
Well data/logs

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#65]
- [ ] Descriptive statistics for raw log data
    - Facies(?)
    - NTG
    - Porosity
    - Permeability
    - Water saturation
- [ ] Blocked well data and modelled parameters

**Comment by HansKallekleiv** [comment]
The main work here is to extract the data from RMS.
For plotting the TablePlotter container will probably be sufficient.

**Comment by HansKallekleiv** [comment]
Covered by #70
