### ISSUE TITLE
Volume tables

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#67]
- Volume tables per segment, interval and facies (where applicable)
  - GRV
  - NRV
  - PV
  - HCPV
  - STOIIP/GIIP
- Geogrid vs simgrid vs eclipse

**Comment by HansKallekleiv** [comment]
I'd say this is more or less solved with the current InplaceVolumes container in https://github.com/equinor/webviz-subsurface.
One remaining challenge is how to reference FIPNUM values to zone/regions when comparing Eclipse and RMS volumes

**Comment by anders-kiaer** [comment]
Solved in #13.
