### ISSUE TITLE
Reusable plotting logic separate from plugins?

### ISSUE THREAD

**Issue by mhwaage** [equinor/webviz-subsurface#737]
In our ongoing [project](https://github.com/equinor/caramba-webviz), we are attempting to make a plugin that can display simulation results (e.g. from an smry file) together with production data obtained via an API. The immediate goal is to allow users to upload a smry file, read it into memory, and display a fanchart from that file together with production data.

Our first approach would have been to import the existing ReservoirTimeSeries plugin, but that cannot support our use case since
1. It expects all files to be known before launching the server
2. We can not configure it to take in additional plots from our production data.

As a next approach, we would like to reuse _functions_ used by the plugin to create the underlying plots. Unfortunately, I can't seem to find a clean way to do this either. Unfortunately, it appears that the loading of csv files etc is done fairly directly in the __init__ of the plugin, making it hard to extract the reading/loading for our use case.

 Would it be possible to decouple the plugin from the plotting logic slightly, so it is easier to reuse? Or  am I missing something, and this is already possible?

**Comment by anders-kiaer** [comment]
I think this is a good idea @mhwaage. What do you think @jorgenherje? Is this something to include in the ongoing restructuring work (#698) of the `ReservoirTimeSeries` plugin?

**Comment by mhwaage** [comment]
This issue is stale, and no longer relevant for my project - I suspect also not very relevant for Webviz anymore either. Closing.
