### ISSUE TITLE
Production misfit plugin

### ISSUE THREAD

**Issue by rnyb** [equinor/webviz-subsurface#754]
Create a plugin to plot production data misfit and coverage at specified dates:
- Prod misfit quantification and ranking of realizations in an ensemble
- Coverage plot of wells in an ensemble. 
- 
Read data from ecl/flow summary files (or optionally from pre-processed csv file)
Use well cummulative oil/water/gas prod data 

Example of misfit/ranking plot:
![image](https://user-images.githubusercontent.com/51825893/131665471-85d6356f-0daa-4322-9b68-2fca45490d5b.png)

Example of coverage plot (1):
![image](https://user-images.githubusercontent.com/51825893/131665690-f7edcdb1-838b-4e67-93c2-613b4ff0509d.png)

Example of coverage plot (2):
![image](https://user-images.githubusercontent.com/51825893/131665909-c7d42477-62df-4d9f-87c4-661c0b44faa6.png)

**Comment by asnyv** [comment]
Nice :) Have been trying to write down my thoughts below.

Some suggestions:

For the first two points, I think there already exists similar jupyter notebooks? But in webviz it might be feasible to combine them in one plugin? 
- Option to do the same thing per group and field as well (in addition to wells) (Think this already exists as a separate notebook)
- Similar plots for pressures (potentially both downhole and in production system, but might be rare that networks downstream of wellhead is used in the historical part?)
- In the bar charts on the top: when multiple phases are present, maybe we could have stacked columns in green, red and blue to show the contribution from each phase?
- Option to change the form of misfit, like absolute misfit, normalized (assuming we have uncertainty in the observation)


Questions:
- How should we define the observed data? In the preprocessing for the jupyter version, the historical data is extracted from the vectors ending with H. I have seen that allocation uncertainty (by modifying historical rates) is sometimes used in AHM, in which case the historical vectors will differ between realizations and iterations (and likely none of them equal to the allocated rate). Should we consider other input formats for the observation (e.g. something like the observation format we have in other plugins?). The downside is that it requires more effort from the users.
- Should we expose how the phases are weighted? Natural weighting is maybe similar to o.e. by dividing gas on 1000? (assuming that the input is metric and not e.g. bbl and scf).


Other ideas for the future:
- Support tracers (would think that it is pretty much the same concept to implement)?
- Misfit for ratios as well (WGR, GLR, GOR, WCT and etc)?

**Comment by rnyb** [comment]
I support your suggestions - looks like we're thinking down the same line - I will aim to incorporate them

> How should we define the observed data?
I think if we can use the summary data directly it will be a benefit ("universal" data - work out of the box). In the special case of varying hist rates per realization it may be solvable to use the mean value of hist in the coverage plot (and/or in combination with hist errorbar/p10-p90) and for misfit quantification we can use a one to one (i.e. use hist vector per realization). It would be very interesting to test out on such a case.

> Should we expose how the phases are weighted?
I think yes, so the user can play along with it if wanted. ~Bg value could be a good place to start for weight (reservoir volume equivalent). in addition we could add option for plotting misfit per phase
