### ISSUE TITLE
`dcc.Slider` with non-string keys in `marks`

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#796]
@rnyb has observed that `marks` should be of format `Dict[str, str]` (https://dash.plotly.com/dash-core-components/slider). Not complying with this could return in non-json-serializable errors. Might be related to https://github.com/plotly/dash/issues/1760.

Hits on `wcc.Slider`: https://github.com/equinor/webviz-subsurface/search?q=%22wcc.Slider%22

**Comment by rnyb** [comment]
Fails with ParameterAnalysis and BhpQc plugins

**Comment by anders-kiaer** [comment]
Perfect - nothing is better - then we can close this.
