### ISSUE TITLE
Remove markers from realization traces in new `SimulationTimeSeries` plugin

### ISSUE THREAD

**Issue by jorgenherje** [equinor/webviz-subsurface#903]
Remove markers from the realization traces for the new simulation time series plugin. 

The current creation of vector realization traces adds `"marker": {"color": color}` to the trace, in `create_vector_realization_traces()`-method in `webviz_subsurface/plugins/_simulation_time_series/utils/create_vector_traces_utils.py`

---
### Issue
Markers are added to realization traces for the simulation time series plugin. Note that when the sampling frequency is high, e.g. higher than Yearly or Quarterly, the markers are automatically disabled by plotly (as `"mode"` is not set to `"lines+markers"`)

**Issue:**
![image](https://user-images.githubusercontent.com/82032112/147910521-b790463b-ad9c-47a7-868f-16888098ca65.png)

**Want:**
![image](https://user-images.githubusercontent.com/82032112/147910547-838cc5d4-173b-4967-9e10-f8275bd8e067.png)

---
### Solution
Markers not wanted, thereby, the key should be removed and color argument must be added to line-settings.
Remove  `"marker": {"color": color}` and add `"color": color` as value to the `"line"`-key.

**Comment by styles3544** [comment]
I'm working on this issue.

**Comment by jorgenherje** [comment]
Minor fix added in code refactoring: https://github.com/equinor/webviz-subsurface/pull/1086
