### ISSUE TITLE
Improved error message when `DATES` is not sorted?

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#979]
Currently we raise https://github.com/equinor/webviz-subsurface/blob/d57bc2e697b0329c01dc24ef97cc7af0aea1228e/webviz_subsurface/_providers/ensemble_summary_provider/_provider_impl_arrow_lazy.py#L135-L136 when dates is not sorted.

A user got this error message on real data. After debugging, it turned out that the raw `.UNSMRY` file (which was converted to `.arrow`) contained some `datetimes` representing the same second when read through `ecl.summary.EclSum.dates`:
```
[...,datetime.datetime(2015, 11, 1, 5, 16, 42), datetime.datetime(2015, 11, 1, 5, 16, 42), ...]
```
The reason for this was that the user had the following in the simulation input schedule setup:
```
DATES
 1 NOV 2015 05:16:43.0000 /
/

--- WCONHIST
--- SOME DATA HERE
--- /

DATES
 1 NOV 2015 05:16:43.000100 /
/
```

If we are to not support this detailed resolution, we could perhaps change from "not sorted" in the error message to say it is not monot. increasing, and/or state which of the time steps this requirement is first failing on (which would help in debugging the simulation setup).

**Comment by anders-kiaer** [comment]
What do you think @sigurdp @berland. We have had two different users (with two different causes - DST schedule and convergence problems) giving same-second-time-step (which are then identical time steps due to second resolution). This again makes the table ambiguous in the sense that we have multiple instances of the _same_ time step after each other.

"Fix" the data on `ecl2df` output generation, or in each consumer? I expect monotonically increasing `x` axis (DATES) would be a common assumption in many consumer use cases.

**Comment by berland** [comment]
See https://github.com/equinor/ecl2df/issues/391

No pretty solution exists as long as it is not supported by libecl.

**Comment by anders-kiaer** [comment]
As for now, @sigurdp assigned to this issue wrt. improving error message only in `webviz-subsurface`.
* Change from "not sorted" to "not monotonically increasing".
* Tell the user which REAL that is problematic and e.g. the two neighboring time steps breaking the mon. inc. assumption.

**Comment by asnyv** [comment]
Just to make it clear: in addition to REAL, also add which ensemble

**Comment by anders-kiaer** [comment]
Improved error message done in #1015.
